name: Build Frontend

on:
  push:
    branches:
      - main
      - work
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        if: ${{ hashFiles('frontend/package.json') != '' }}
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Build frontend
        if: ${{ hashFiles('frontend/package.json') != '' }}
        run: npm run build
      - name: Deploy to gh-pages
        if: ${{ hashFiles('frontend/package.json') != '' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build
          publish_branch: gh-pages

